server:
  port: 8001

#management:
#  security:
#    enabled: false

spring:
  application:
    name: spring-boot-jpa-template

  datasource:
#    data: classpath:db/data.sql
#    schema: classpath:db/schema.sql
#    hikari:
#      jdbc-url: jdbc:h2:mem:h2test
#      driver-class-name: org.h2.Driver
#      username: zbook
#      password: zbook
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:h2test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    # org.hibernate.dialect.MySQL5InnoDBDialect
    database: h2
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: validate
  data:
    jpa:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console/h2test
